"""add conversation document scope

Revision ID: 4a25d5af7b4f
Revises: c8e57ac164d2
Create Date: 2026-10-05 06:52:30.497263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a25d5af7b4f'
down_revision: Union[str, Sequence[str], None] = 'c8e57ac164d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'projects', ['project_id'], ['id'])
    op.add_column('documents', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.alter_column('documents', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'documents', 'conversations', ['conversation_id'], ['id'])
    op.create_check_constraint('check_document_scope', 'documents', '\n      (project_id IS NOT NULL AND conversation_id IS NULL)\n      OR\n      (project_id IS NULL AND conversation_id IS NOT NULL)\n      ')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_document_scope', 'documents', type_='check')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.alter_column('documents', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('documents', 'conversation_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'project_id')
    # ### end Alembic commands ###
