"""add project id to documents

Revision ID: c8e57ac164d2
Revises: a18e3485f958
Create Date: 2026-10-03 06:35:18.862327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e57ac164d2'
down_revision: Union[str, Sequence[str], None] = 'a18e3485f958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'project_id')
    # ### end Alembic commands ###
